server:
  port: 520
  servlet:
    context-path: /cupid/portal
spring:
  application:
    name: cupid-portal
  profiles:
    active: @profile@
management:
  endpoints:
    web:
      exposure:
        include: "*"



security:
  login:
    url: "/login"
  logout:
    url: "/logout"